from fyers_apiv3 import fyersModel

client_id = "MMKQTWNJH3-100"
access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE3MzI1NTc1OTcsImV4cCI6MTczMjU4MTA1NywibmJmIjoxNzMyNTU3NTk3LCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCblJMc2Qya2ZjYmh3dzRqSjlTN3Btb1llYzZvZTRNaXN2d2V0czZpZEZ2OE52YTlBWjVJYWVQWXJEbUJqQVZFWjQ0V3hKRVJBQ0l1WEpWSVJvMm95aGYwMXBsZEhZRWl4WTJrc0RXcjlJT0FuS3pSVT0iLCJkaXNwbGF5X25hbWUiOiJBS0lMIFRIQU5HQVZFTCIsIm9tcyI6IksxIiwiaHNtX2tleSI6ImJlY2M0NDU4NmZjN2MyOTFhMWZjYTAwZmVjMjA2YmQ0MjNiOThlZDRiYWY4Mjc3YjZhMWI5Y2U2IiwiZnlfaWQiOiJZQTI5Mzk2IiwiYXBwVHlwZSI6MTAwLCJwb2FfZmxhZyI6Ik4ifQ.dkRi7N4M_cYMFpYqmLCSLV-d9eGuQSnKZ5tDvNeXSyE"
# Initialize the FyersModel instance with your client_id, access_token, and enable async mode
fyers = fyersModel.FyersModel(client_id=client_id, token=access_token,is_async=False, log_path="")

data = {
    "symbols":"NSE:SBIN-EQ,NSE:IDEA-EQ"
}

response = fyers.quotes(data=data)
print(response)